version: "3"
services:
  steamcmd:
    container_name: neosvr-headless
    build:
      context: .
      args:
        - STEAMBETAPASS=
        - STEAMLOGIN=
        - STEAMPASS=
    network_mode: "host"
    tty: true
    stdin_open: true
    volumes:
      - "./Config:/usr/games/neosvr-headless/Config"
      - "./Logs:/usr/games/neosvr-headless/Logs"
      - "./Libraries:/usr/games/neosvr-headless/Libraries"
      - "./nml_mods:/usr/games/neosvr-headless/nml_mods"
      - "./nml_libs:/usr/games/neosvr-headless/nml_libs"
      - "./Scripts:/usr/games/neosvr-headless/Scripts"
      - "/etc/localtime:/etc/localtime:ro"